version: '3'

services:
  node0:
    container_name: hhubnode0
    image: "hhub/node"
    ports:
      - "26656-26657:26656-26657"
      - "8545-8546:8545-8546"
    volumes:
      - ./build/node0/hhubd:/hhub:Z
    command:
      - /hhubd start --home /hhub
    networks:
      localnet:
        ipv4_address: 192.167.10.2

  node1:
    container_name: hhubnode1
    image: "hhub/node"
    ports:
      - "26659-26660:26656-26657"
      - "8547-8548:8545-8546"
    volumes:
      - ./build/node1/hhubd:/hhub:Z
    command:
      - /hhubd start --home /hhub
    networks:
      localnet:
        ipv4_address: 192.167.10.3

  node2:
    container_name: hhubnode2
    image: "hhub/node"
    ports:
      - "26661-26662:26656-26657"
      - "8549-8550:8545-8546"
    volumes:
      - ./build/node2/hhubd:/hhub:Z
    command:
      - /hhubd start --home /hhub
    networks:
      localnet:
        ipv4_address: 192.167.10.4

  node3:
    container_name: hhubnode3
    image: "hhub/node"
    ports:
      - "26663-26664:26656-26657"
      - "8551-8552:8545-8546"
    volumes:
      - ./build/node3/hhubd:/hhub:Z
    command:
      - /hhubd start --home /hhub
    networks:
      localnet:
        ipv4_address: 192.167.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 192.167.10.0/16